//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package graph

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Channel) DeepCopyInto(out *Channel) {
	*out = *in
	out.Partitioning = in.Partitioning
	if in.Feedback != nil {
		in, out := &in.Feedback, &out.Feedback
		*out = new(Feedback)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Channel.
func (in *Channel) DeepCopy() *Channel {
	if in == nil {
		return nil
	}
	out := new(Channel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Feedback) DeepCopyInto(out *Feedback) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Feedback.
func (in *Feedback) DeepCopy() *Feedback {
	if in == nil {
		return nil
	}
	out := new(Feedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Partitioning) DeepCopyInto(out *Partitioning) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Partitioning.
func (in *Partitioning) DeepCopy() *Partitioning {
	if in == nil {
		return nil
	}
	out := new(Partitioning)
	in.DeepCopyInto(out)
	return out
}
